### ISSUE TITLE
PreTrained model keys dismatch

### ISSUE THREAD

**Issue by leonardozcm** [diviswen/PMP-Net#7]
```
Traceback (most recent call last):
  File "runner.py", line 130, in <module>
    CandiModel("PMPNet", loadParallelModel(PMPNet(),"checkpoint/pmpnet.pth") ),
  File "runner.py", line 39, in loadParallelModel
    print(model.load_state_dict(checkpoint[keyname]))
  File "/home/chriskafka/anaconda3/envs/ML/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.step_1.sa_module_1.mlp_conv.0.conv.weight: copying a param with shape torch.Size([64, 9, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 6, 1, 1]).
        size mismatch for module.step_1.fp_module_1.mlp_conv.0.conv.weight: copying a param with shape torch.Size([128, 137, 1]) from checkpoint, the shape in current model is torch.Size([128, 134, 1]).
```

I only test pretrained-model of pcn, and turns out failure. Would you mind checking out if the model you provide on Google drive is right? thanks a lot.

**Comment by MatlabChen** [comment]
same problem
